Repository miragejs/ember-cli-mirage, pull requests merged in 2022-01, with the labels that each got.

#2297 remove some usage of runtime require
  addon/get-rfc232-test-context.js
  addon/utils/ember-data.js
  package.json
  yarn.lock
Labels: Feature / Enhancement

#2256 Deprecate miragejs re-exports from `ember-cli-mirage/*` modules
  addon/association.js
  addon/db-collection.js
  addon/db.js
  addon/deprecate-imports.js
  addon/deprecate-reexports.js
  addon/ember-data.js
  addon/factory.js
  addon/identity-manager.js
  addon/index.js
  addon/orm/associations/association.js
  addon/orm/associations/belongs-to.js
  addon/orm/associations/has-many.js
  addon/orm/collection.js
  addon/orm/model.js
  addon/orm/polymorphic-collection.js
  addon/orm/schema.js
  addon/response.js
  addon/route-handler.js
  addon/route-handlers/base.js
  addon/route-handlers/function.js
  addon/route-handlers/object.js
  addon/route-handlers/shorthands/base.js
  addon/route-handlers/shorthands/delete.js
  addon/route-handlers/shorthands/get.js
  addon/route-handlers/shorthands/head.js
  addon/route-handlers/shorthands/post.js
  addon/route-handlers/shorthands/put.js
  addon/serializer-registry.js
  addon/serializer.js
  addon/serializers/active-model-serializer.js
  addon/serializers/json-api-serializer.js
  addon/serializers/rest-serializer.js
  addon/trait.js
  addon/utils/extend.js
  addon/utils/inflector.js
  addon/utils/is-association.js
  addon/utils/read-modules.js
  addon/utils/reference-sort.js
  addon/utils/uuid.js
  package.json
  tests/dummy/app/pods/docs/getting-started/upgrade-guide/index/template.md
  tests/dummy/app/pods/docs/getting-started/upgrade-guide/v2-deprecations/template.md
Labels: Feature / Enhancement

#2300 Pin colors transitive dependency to fix CI
  package.json
  yarn.lock
Labels: Dependencies

#2302 Added a publish to NPM on tag create as a github action
  .github/workflows/publish.yml
Labels: internal

#2304 Switch to yarn with frozen lockfile to run publish workflow
  .github/workflows/publish.yml
Labels: internal

#2309 Added docs deploy as a github action
  .github/workflows/deploy.yml
Labels: internal

#2306 Fix deprecation message for `ember-cli-mirage/utils/uuid` import
  addon/utils/uuid.js
Labels: Bug

#2311 Bump ember-auto-import from 1.12.0 to 2.2.4
  package.json
  yarn.lock
Labels: Breaking

#2312 Drop support for legacy Node.js versions 10, 11, 13, 15
  package.json
Labels: Breaking

#2313 Widen `ember-get-config` dependency requirement (include v1.0.0)
  package.json
  yarn.lock
Labels: Feature / Enhancement

#2315 Run `npx ember-cli-update --to=4.1.0` to sync with the latest blueprint
  .eslintignore
  .eslintrc.js
  .github/workflows/ci.yml
  .gitignore
  .node-version
  .npmignore
  .prettierignore
  README.md
  config/ember-try.js
  package.json
  test-projects/01-basic-app/.gitignore
  test-projects/01-basic-app/config/ember-cli-update.json
  test-projects/01-basic-app/config/targets.js
  test-projects/01-basic-app/package.json
  test-projects/02-app-that-excludes-mirage/.gitignore
  test-projects/02-app-that-excludes-mirage/config/ember-cli-update.json
  test-projects/02-app-that-excludes-mirage/config/targets.js
  test-projects/02-app-that-excludes-mirage/package.json
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/targets.js
  yarn.lock
Labels: internal

#2323 Point users of deprecated inflector methods to ember-inflector
  addon/utils/inflector.js
Labels: Bug

#2324 Point users of deprecated inflector methods to ember-inflector
  addon/utils/inflector.js
Labels: Bug

#2327 Bump @embroider/* packages to 1.0.0
  package.json
  yarn.lock
Labels: Dependencies

#2329 Deprecate the routes only version of the config
  addon/start-mirage.js
  test-projects/01-basic-app/config/environment.js
  tests/dummy/app/pods/docs/advanced/server-configuration/template.md
Labels: Feature / Enhancement

#2314 Remove deprecated `miragejs` re-exports
  addon/association.js
  addon/db-collection.js
  addon/db.js
  addon/deprecate-imports.js
  addon/deprecate-reexports.js
  addon/factory.js
  addon/identity-manager.js
  addon/index.js
  addon/orm/associations/association.js
  addon/orm/associations/belongs-to.js
  addon/orm/associations/has-many.js
  addon/orm/collection.js
  addon/orm/model.js
  addon/orm/polymorphic-collection.js
  addon/orm/schema.js
  addon/response.js
  addon/route-handler.js
  addon/route-handlers/base.js
  addon/route-handlers/function.js
  addon/route-handlers/object.js
  addon/route-handlers/shorthands/base.js
  addon/route-handlers/shorthands/delete.js
  addon/route-handlers/shorthands/get.js
  addon/route-handlers/shorthands/head.js
  addon/route-handlers/shorthands/post.js
  addon/route-handlers/shorthands/put.js
  addon/serializer-registry.js
  addon/serializer.js
  addon/serializers/active-model-serializer.js
  addon/serializers/json-api-serializer.js
  addon/serializers/rest-serializer.js
  addon/trait.js
  addon/utils/extend.js
  addon/utils/inflector.js
  addon/utils/is-association.js
  addon/utils/reference-sort.js
  addon/utils/uuid.js
  test-projects/01-basic-app/tests/acceptance/ember-data-test.js
  tests/unit/inflector-test.js
Labels: Breaking

#2341 Removed the ember-li-mirage Server. Must use MirageJS createServer from the mirage/config.js
  addon/server.js
  addon/start-mirage.js
  app/initializers/ember-cli-mirage.js
  blueprints/ember-cli-mirage/files/__root__/config.js
  test-projects/01-basic-app/mirage/config.js
  test-projects/01-basic-app/tests/acceptance/ember-data-test.js
  test-projects/01-basic-app/tests/acceptance/legacy-start-mirage-test.js
  test-projects/02-app-that-excludes-mirage/mirage/config.js
  tests/dummy/app/pods/docs/getting-started/overview/template.md
  tests/dummy/app/pods/docs/getting-started/upgrade-guide/index/template.md
  tests/dummy/app/pods/docs/getting-started/upgrade-guide/v2-deprecations/template.md
  tests/unit/serializers/ember-data-serializer-test.js
Labels: Breaking

#2344 Add usage notes for Embroider to documentation
  tests/dummy/app/pods/docs/getting-started/installation/template.md
Labels: Documentation
