Repository miragejs/ember-cli-mirage, pull requests merged in 2023-10, with the labels that each got.

#2542 feat: access Ember Data models via Store service
  packages/ember-cli-mirage-docs/app/templates/docs/advanced/environment-options.md
  packages/ember-cli-mirage-docs/app/templates/docs/advanced/server-configuration.md
  packages/ember-cli-mirage-docs/app/templates/docs/getting-started/upgrade-guide/index.md
  packages/ember-cli-mirage-docs/app/templates/docs/testing/setup-mirage.md
  packages/ember-cli-mirage-docs/mirage/config.js
  packages/ember-cli-mirage/addon/ember-data.js
  packages/ember-cli-mirage/addon/start-mirage.js
  packages/ember-cli-mirage/blueprints/ember-cli-mirage/files/__root__/config.js
  packages/ember-cli-mirage/package.json
  packages/ember-cli-mirage/tests/dummy/config/ember-try.js
  packages/ember-cli-mirage/tests/dummy/mirage/config.js
  packages/ember-cli-mirage/tests/unit/models/ember-data-model-discover-test.js
  pnpm-lock.yaml
  test-packages/01-basic-app/mirage/config.js
  test-packages/01-basic-app/package.json
  test-packages/01-basic-app/tests/acceptance/ember-data-test.js
  test-packages/02-app-that-excludes-mirage/mirage/config.js
Labels: Feature / Enhancement

#2546 Update v3 upgrade guide
  packages/ember-cli-mirage-docs/app/templates/docs/advanced/environment-options.md
  packages/ember-cli-mirage-docs/app/templates/docs/data-layer/database.md
  packages/ember-cli-mirage-docs/app/templates/docs/data-layer/factories.md
  packages/ember-cli-mirage-docs/app/templates/docs/data-layer/models.md
  packages/ember-cli-mirage-docs/app/templates/docs/data-layer/relationships.md
  packages/ember-cli-mirage-docs/app/templates/docs/data-layer/serializers/ember-data-serializer.md
  packages/ember-cli-mirage-docs/app/templates/docs/data-layer/serializers/index.md
  packages/ember-cli-mirage-docs/app/templates/docs/getting-started/installation.md
  packages/ember-cli-mirage-docs/app/templates/docs/getting-started/upgrade-guide.md
  packages/ember-cli-mirage-docs/app/templates/docs/testing/assertions.md
Labels: Documentation

#2552 Use markdown links format
  packages/ember-cli-mirage-docs/app/templates/docs/data-layer/database.md
  packages/ember-cli-mirage-docs/app/templates/docs/data-layer/models.md
  packages/ember-cli-mirage-docs/app/templates/docs/data-layer/relationships.md
  packages/ember-cli-mirage-docs/app/templates/docs/data-layer/serializers/index.md
Labels: Documentation

#2559 Restore usingProxy config
  packages/ember-cli-mirage/config/environment.js
Labels: Bug

#2562 Fix usingProxy() on Windows
  packages/ember-cli-mirage/config/environment.js
Labels: Bug
