Repository miragejs/ember-cli-mirage, pull requests merged in 2023-09, with the labels that each got.

#2508 install ember-tether in docs app
  packages/ember-cli-mirage-docs/package.json
  pnpm-lock.yaml
Labels: Dependencies

#2421 ➖ Remove `lodash` dependency
  packages/ember-cli-mirage/addon/serializers/ember-data-serializer.js
  packages/ember-cli-mirage/package.json
  pnpm-lock.yaml
Labels: Feature / Enhancement

#2509 remove ember-destroyable-polyfill dependency
  packages/ember-cli-mirage/package.json
  pnpm-lock.yaml
Labels: Dependencies

#2417 Make MirageJS peer dependency
  README.md
  packages/ember-cli-mirage-docs/app/templates/docs/getting-started/installation.md
  packages/ember-cli-mirage/blueprints/ember-cli-mirage/index.js
  packages/ember-cli-mirage/package.json
  pnpm-lock.yaml
  test-packages/01-basic-app/package.json
  test-packages/02-app-that-excludes-mirage/package.json
Labels: Breaking, Documentation

#2457 Updated blueprint and guide for missing import
  packages/ember-cli-mirage-docs/app/templates/docs/getting-started/upgrade-guide/index.md
  packages/ember-cli-mirage/blueprints/ember-cli-mirage/files/__root__/config.js
Labels: Bug

#2355 Detect @ember-data/model instead of ember-data meta-package
  packages/ember-cli-mirage/addon/utils/ember-data.js
  packages/ember-cli-mirage/package.json
  pnpm-lock.yaml
Labels: Feature / Enhancement

#2334 Export default in server docs
  packages/ember-cli-mirage-docs/app/templates/docs/advanced/server-configuration.md
Labels: Documentation

#1948 Use native setters in documentation examples
  packages/ember-cli-mirage-docs/app/templates/docs/testing/integration-and-unit-tests.md
Labels: Documentation

#2335 Export default in server docs
  tests/dummy/app/pods/docs/advanced/server-configuration/template.md
Labels: Documentation

#2511 bump ember-cli-addon-docs from 6.0.1 to 6.0.2
  packages/ember-cli-mirage-docs/package.json
  packages/ember-cli-mirage/package.json
  pnpm-lock.yaml
Labels: Dependencies

#2517 bump release-it and plugins
  package.json
  pnpm-lock.yaml
Labels: Dependencies

#2518 bump @babel/core from 7.22.10 to 7.22.17
  packages/ember-cli-mirage-docs/package.json
  packages/ember-cli-mirage/package.json
  pnpm-lock.yaml
  test-packages/01-basic-app/package.json
  test-packages/02-app-that-excludes-mirage/package.json
Labels: Dependencies

#2519 bump concurrently from 8.0.1 to 8.2.1
  packages/ember-cli-mirage-docs/package.json
  packages/ember-cli-mirage/package.json
  pnpm-lock.yaml
  test-packages/01-basic-app/package.json
  test-packages/02-app-that-excludes-mirage/package.json
Labels: Dependencies

#2520 bump fastboot from 3.3.0 to 4.1.1
  packages/ember-cli-mirage/package.json
  pnpm-lock.yaml
  test-packages/01-basic-app/package.json
Labels: Dependencies

#2521 bump ember-cli-deploy from 1.0.2 to 2.0.0
  packages/ember-cli-mirage-docs/package.json
  pnpm-lock.yaml
Labels: Dependencies

#2522 bump ember-cli-babel from 7.26.11 to 8.0.0
  package.json
  packages/ember-cli-mirage-docs/package.json
  packages/ember-cli-mirage/package.json
  pnpm-lock.yaml
  test-packages/01-basic-app/package.json
  test-packages/02-app-that-excludes-mirage/package.json
Labels: Dependencies
