Repository miragejs/ember-cli-mirage, pull requests merged in 2024-09, with the labels that each got.

#2578 add v5.x to the list of ember-inflector versions
  packages/ember-cli-mirage/package.json
  pnpm-lock.yaml
Labels: Feature / Enhancement

#2583 Add v5.4 LTS to CI matrix
  .github/workflows/ci.yml
  README.md
  packages/ember-cli-mirage/tests/dummy/config/ember-try.js
Labels: internal

#2584 Bump release-it and plugins
  package.json
  pnpm-lock.yaml
Labels: Dependencies

#2585 Fix publish workflow
  .github/workflows/publish.yml
Labels: internal
